apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Alias
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack-alias
spec:
  name: prod
  functionRef: 
    from: 
      name: lambda-oci-ack
  functionVersion: lambda-oci-ack-version-6