apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- function.yaml
images:
- name: 54459206677.dkr.ecr.us-west-2.amazonaws.com/hello-world
  newName: 54459206677.dkr.ecr.us-west-2.amazonaws.com/hello-world
  newTag: bufsadf
configurations:
- kustomizeconfig/mykind.yaml
