apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack
spec:
  code:
    imageURI: 54459206677.dkr.ecr.us-west-2.amazonaws.com/hello-world:f78ee911a36ab12cde1160e6d3a3aa7745e5e2b7
  description: function created by ACK lambda-controller e2e tests
  name: lambda-oci-ack
  packageType: Image
  role: arn:aws:iam::54459206677:role/lambda_basic_execution
