apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack
spec:
  code:
    imageURI: 544592066775.dkr.ecr.us-west-2.amazonaws.com/lambda-repo:39402266b9984f935b6dab2380b036e7498f3308
  description: function created by ACK lambda-controller e2e tests
  name: lambda-oci-ack
  packageType: Image
  role: arn:aws:iam::544592066775:role/lambda_basic_execution
