apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack
spec:
  code:
    imageURI: 54459206677.dkr.ecr.us-west-2.amazonaws.com/hello-world:4eb2092cefd86dd7fe348864754808aab5b4cbb8
  description: function created by ACK lambda-controller e2e tests
  name: lambda-oci-ack
  packageType: Image
  role: arn:aws:iam::54459206677:role/lambda_basic_execution
