apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack
spec:
  code:
    imageURI: 544592066775.dkr.ecr.us-west-2.amazonaws.com/lambda-repo:cad41b55e21b871736fbc52ef3a0102b9c707d3c
  description: function created by ACK lambda-controller e2e tests
  name: lambda-oci-ack
  packageType: Image
  role: arn:aws:iam::544592066775:role/lambda_basic_execution
