apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  annotations:
    services.k8s.aws/region: us-west-2
  name: lambda-oci-ack
spec:
  code:
    imageURI: 544592066775.dkr.ecr.us-west-2.amazonaws.com/lambda-repo:8fe7fc9d94b3443165d997dfcb2fcdc67e059e11
  description: function created by ACK lambda-controller e2e tests
  name: lambda-oci-ack
  packageType: Image
  role: arn:aws:iam::544592066775:role/lambda_basic_execution
